config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :language
end

app/models/language.rb
class Language < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'Ruby on Rails' },
    { id: 3, name: 'HTML' },
    { id: 4, name: 'CSS' },
    { id: 5, name: 'React' },
    { id: 6, name: 'PHP' },
    { id: 7, name: 'Python' },
    { id: 8, name: 'Java' },
    { id: 9, name: 'JavaScript' }
  ]
  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = Item.all.order(created_at: :desc)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private
  def item_params
    params.require(:item).permit(:language_id, :title, :content).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path      
    else
      render :edit
    end
  end
 
  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<%= render "shared/header" %>

<div class="edit-wrapper">
  <div class="edit-main">
    <div class="edit-nav">
      <span><%= link_to "戻る", item_path(@item.id) %></span>
    </div>
    <div class="edit-conetents">
      <%= form_with model: @item, local: true do |f| %>
        <h1 class="edit-language">言語</h1>
        <div><%= f.collection_select(:language_id, Language.all, :id, :name, {}, { class: "edit-detail-language" }) %></div>
        <h1 class="edit-title">タイトル</h1>
        <div><%= f.text_field :title, class: "edit-detail-title", placeholder: "タイトルを入力" %></div>
        <h1 class="edit-content">内容</h1>
        <div><%= f.text_area :content, class: "edit-detail-content" %></div>
        <div><%= f.submit "更新", class: "edit-btn" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<%# ヘッダー %>
<%= render "shared/header" %>
<div class="index-wrapper">
  <%# メインコンテンツ %>
  <div class="index-contents">
    <div class="index-lists">
      <h1>items controller index action page</h1>
      <% @items.each do |item| %>
        <%= link_to item_path(item.id) do %>
          <div>
            <%= item.language.name %>
          </div>
        <% end %>
        <%#
          <div>
            <%= item.title 
          </div>
          <div>
            <%= item.content
          </div>
        %>
      <% end %>
    </div>
    <%# フッター %>
    <%#= render "shared/footer" %>
  </div>
</div>

app/views/items/new.html.erb
<%= render "shared/header" %>
<h1>items controller new action page</h1>
<span><%= link_to "トップページ", root_path %></span>
<%= form_with model: @item, local: true do |f| %>
  <div>言語</div>
  <%= f.collection_select(:language_id, Language.all, :id, :name, {}) %>
  <div>タイトル</div>
  <%= f.text_field :title, placeholder: "タイトルを入力" %>
  <div>内容</div>
  <%= f.text_area :content %>
  <%= f.submit "送信" %>
<% end %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="show-wrapper">
  <div class="show-main">
    <div class="show-nav">
        <div><%= link_to "戻る", root_path , class: "show-item-return" %></div>
        <div class="show-menu">
          <div><%= link_to "編集", edit_item_path(@item.id), method: :get,class: "show-item-edit" %></div>
          <div><%= link_to "削除", item_path(@item.id), method: :delete, class: "show-item-delete" %></div>
        </div>
    </div>
    <div class="show-contents">
      <div>
        <h1 class="show-language">言語<h1>
        <div class="show-detail-language"><%= @item.language.name %></div>
      </div>
      <div>
        <h1 class="show-title">タイトル</h1>
        <div class="show-detail-title"><%= @item.title %></div>
      </div>
      <div>
        <h1 class="show-content">内容</h1>
        <div class="show-detail-content"><%= simple_format(h(@item.content), class: "show-detail-content") %></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTextbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header-title">
    <h3><%= link_to "My TextBook", root_path, class: "header-title-name" %></h3>
  </div>
  <div class="header-user-nav">
    <ul class="header-nav-list">
      <% if user_signed_in? %> 
        <li><%= link_to "新規投稿", new_item_path, class:"header-new-post" %></li>
        <li><%= link_to current_user.nickname, "#", class: "header-user-name" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "header-login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "header-sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>